"""Mako template for Alembic autogenerate."""

"""add_chains_and_chain_tvl_columns

Revision ID: 5fb7d60f638a
Revises: 6c2748694ef3
Create Date: 2026-05-12 06:13:25.033503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb7d60f638a'
down_revision: Union[str, None] = '6c2748694ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('chains', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('chain_tvl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'chain_tvl')
    op.drop_column('projects', 'chains')
    # ### end Alembic commands ###
