"""Mako template for Alembic autogenerate."""

"""initial_schema

Revision ID: 6c2748694ef3
Revises: 
Create Date: 2026-05-12 05:59:29.577113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2748694ef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('projects_upserted', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('api_calls_made', sa.Integer(), nullable=False),
    sa.Column('api_errors', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('chain', sa.String(length=100), nullable=True),
    sa.Column('has_token', sa.Boolean(), nullable=False),
    sa.Column('current_tvl', sa.Float(), nullable=True),
    sa.Column('tvl_growth_30d_pct', sa.Float(), nullable=True),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('source_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('alert_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('score_at_alert', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_queue_unsent', 'alert_queue', ['sent', 'created_at'], unique=False)
    op.create_table('funding_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('round_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('round_type', sa.String(length=100), nullable=True),
    sa.Column('lead_investor', sa.String(length=255), nullable=True),
    sa.Column('investors', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('commit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'commit_hash', 'keyword', name='uq_github_signal')
    )
    op.create_table('project_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.String(length=50), nullable=False),
    sa.Column('outcome_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score_at_outcome', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('tvl_points', sa.Float(), nullable=False),
    sa.Column('growth_points', sa.Float(), nullable=False),
    sa.Column('funding_points', sa.Float(), nullable=False),
    sa.Column('github_points', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_history_project_scored', 'score_history', ['project_id', 'scored_at'], unique=False)
    op.create_table('tvl_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tvl_usd', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tvl_snapshots_project_recorded', 'tvl_snapshots', ['project_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tvl_snapshots_project_recorded', table_name='tvl_snapshots')
    op.drop_table('tvl_snapshots')
    op.drop_index('ix_score_history_project_scored', table_name='score_history')
    op.drop_table('score_history')
    op.drop_table('project_outcomes')
    op.drop_table('github_signals')
    op.drop_table('github_overrides')
    op.drop_table('funding_rounds')
    op.drop_index('ix_alert_queue_unsent', table_name='alert_queue')
    op.drop_table('alert_queue')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('ingestion_metrics')
    # ### end Alembic commands ###
